services:
  relay:
    container_name: sw2-relay
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./templates:/app/templates"
      - "./whitelist.json:/app/whitelist.json"
      - "./read_whitelist.json:/app/read_whitelist.json"
    ports:
      - "3334:3334"